### ISSUE TITLE
Don't set process.env.NODE_ENV

### ISSUE THREAD

**Issue by pksunkara** [sebastian-software/universal-dotenv#1]
From issue storybooks/vue-cli-plugin-storybook#8

Why are you setting it in the first place? Let the users of this module worry about specifiying their NODE_ENV. You just default to `development` with the following code without this [part](https://github.com/sebastian-software/universal-dotenv/blob/master/src/index.js#L7-L12)

```js
const NODE_ENV = process.env.NODE_ENV || 'development';
```

Please fix this and release as soon as possible.

**Comment by swernerx** [comment]
Thanks for contacting me. The issue is a bit minimal on details. I wonder why setting a default, if nothing is set before, is problematic at all. You are still able to set it do any other value you like. It's not write protected.

**Comment by pksunkara** [comment]
Basically, if I intentionally don't set the NODE_ENV because of something I am trying to do, and it loads `@storybook/core`, then my NODE_ENV gets set by your module.

You made a nodejs module. It's nice, but please don't change environments like that. I would understand if the purpose of your module is to do that, but it's not here.

**Comment by swernerx** [comment]
Sounds reasonable. Thanks. I'll check that.

**Comment by swernerx** [comment]
I just released v1.9.0 which does not write to process.env anymore. Can you please check whether this fixes your issue 
https://github.com/storybooks/vue-cli-plugin-storybook/issues/8

**Comment by pksunkara** [comment]
Need to upgrade dependency in storybook. But I tested it locally and it fixed the issue.
