### ISSUE TITLE
Ability to inject all variables into webpack

### ISSUE THREAD

**Issue by sheerun** [sebastian-software/universal-dotenv#3]
Currently this plugin supports only injecting ALL_ prefixed variables into webpack. Could we get an option to include all variables from .env.* files? (excluding variables from system for security)

**Comment by swernerx** [comment]
It injects all variables starting with `APP_`. That's the convention it follows. That's also implemented for the reason of security.

**Comment by sheerun** [comment]
Yes, I mean I have variables in .env.development and .env.production that don't have APP_ prefix and I'd like them to be injected. Currently I must use dotenv-webpack for this use case

**Comment by swernerx** [comment]
We could probably think of some option for the Webpack part. Can you contribute this as a PR?

**Comment by swernerx** [comment]
Closed because of inactivity. Feel free to reopen if there is still any motivation to work on this.
